# Generated by Django 2.0.1 on 2018-01-12 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20180111_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownKeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_text_contains', models.CharField(max_length=200)),
                ('subCatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.SubCatagory')),
            ],
        ),
    ]
