# Generated by Django 2.0.1 on 2018-02-26 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rule_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='subCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.SubCategory'),
        ),
    ]
