# Generated by Django 2.0.1 on 2018-03-06 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20180226_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.InputSource'),
        ),
    ]
