# Generated by Django 2.0.1 on 2018-01-12 11:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('expenses', '0007_auto_20180112_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='SubCatagory',
        ),
    ]
