# Generated by Django 2.0.1 on 2018-03-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20180306_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
