# Generated by Django 2.0.1 on 2018-01-12 11:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('expenses', '0008_auto_20180112_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catagory',
        ),
    ]
