# Generated by Django 2.0.1 on 2018-01-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_auto_20180112_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='txn_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='txn_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='txn_text',
            new_name='text',
        ),
    ]
