# Generated by Django 2.0.1 on 2018-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20180112_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='subcatagory',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.CharField(default='YONIGO', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(default='YONIGO_SOURCE', max_length=200),
            preserve_default=False,
        ),
    ]
