# Generated by Django 2.0.1 on 2018-01-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_auto_20180115_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
            ],
        ),
    ]
