# Generated by Django 2.0.1 on 2018-01-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_inputsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.InputSource'),
        ),
    ]
