# Generated by Django 2.0.1 on 2018-01-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_auto_20180127_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knownkeywords',
            old_name='subCatagory',
            new_name='subCategory',
        ),
    ]
