# Generated by Django 2.0.1 on 2018-01-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_auto_20180127_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputsource',
            old_name='type',
            new_name='type_name',
        ),
    ]
