# Generated by Django 2.0.1 on 2018-01-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_auto_20180127_0842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnownKeyWords',
            new_name='Rule',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='txn_text_contains',
            new_name='text_contains',
        ),
    ]
